### ISSUE TITLE
Pretty printer/lineariser omits explicit typecasts

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1237]
*Issue migrated from trac ticket # 1236*

**component:** Core: Type-checker Library | **priority:** major

#### 2013-11-22 10:46:25: @twillems created the issue

___
The lineariser or the pretty printer omit explicit typecasts in converting mCRL2 files. 

Under certain circumstances, this can introduce type checking errors in the mCRL2 files obtained by linearising and subsequent pretty printing. A small example illustrating the issues is the following:

```
sort A = struct element(id:Nat);

map f: A -> Int;
var a:A; id:Nat;
eqn 
f(a) = Nat2Int(id(a));

init delta;
```

After linearising and pretty-printing the above specification, the resulting code is no longer linearisable. Reusing function names (id) as variable names (id) appears to be a prerequisite in reproducing the issue.

**Comment by jgroote** [comment]
With the previous release type checking of variables has been strengthened in the sense that they cannot coincide anymore with function names. This makes this particular example invalid and
appears to resolve the problem. The lineariser reports:

Reading input from file 'test.mcrl2'...
type checking process specification...
[error]   The variable id:Nat clashes with the user defined function id:A -> Nat.
[error]   This error occurred while typechecking equation f(a)  =  Nat2Int(id(a)).
[error]   Failed to type check data specification.

This means that this ticket can be closed, as it -- at least in the current guise -- has been resolved.

**Comment by tneele** [comment]
The variable `id` is not relevant to the problem at all, so the bug is still there. Take for example the following specification:
```
sort A = struct element(id:Nat);

map f: A -> Int;
var a:A;
eqn 
f(a) = Nat2Int(id(a));

init delta;
```
Running the following command sequence yields:
```
$ mcrl22lps test.mcrl2 | lpspp | mcrl22lps > test2.lps
[error]   Types of the left- (Int) and right- (Nat) hand-sides of the equation f(a)  =  id(a) do not match.
[error]   Failed to type check data specification.
```
In my opinion, this is a valid use case, so the issue should be fixed.

**Comment by jgroote** [comment]
The previous example is convincing. The problem is not solved. Hence, I reopen this issue. 
I feel that a good solution is not easy. We don't want the pretty printer to write 
type converters such as Nat2Int at every place. Yet, adapting the type checker to for sure
insert type convertors everywhere requires an adaption of the typechecker, and a proof that
this typecheck property is never violated. I will bring this example to the attention of Hendrik van 
Antwerpen. I believe it is too much to ask to resolve this problem for the 2018 release, but 
we should keep it on the list.

**Comment by jgroote** [comment]
Taking the last example of Thomas (called tim.mcrl2) and applying 
mcrl22lps tim.mcrl2 | lpspp | mcrl22lps > temp.lps 
does not yield an error anymore.

It appears that eqn  f(a)  =  id(a), which was not properly typed is now properly
typed. Although I do not trust the dark corners of the typechecker at all, this concrete problem
appears to be resolved.
