### ISSUE TITLE
GUI tools produce black text on dark background in dark mode on macOS

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1545]
On macOS in dark mode, mcrl2ide and mcrl2xi show dark text on dark background, making it virtually impossible to read the text.

The following is a screenshot of mcrl2ide that contains text on lines 1, 3 and 5. The issue in mcrl2xi is similar.

<img width="865" alt="Screenshot 2019-07-15 at 08 07 35" src="https://user-images.githubusercontent.com/2182862/61198000-fb8cd100-a6d7-11e9-8803-6e490b8c0f3e.png">

Version information:

```
mcrl2ide --version
mCRL2ide mCRL2 toolset 201808.0.6cc1d16937M (Release)
```

mCRL2 was built agains Qt 5.13.0

**Comment by jgroote** [comment]
Ik denk dat het goed is wanneer Olav hier even naar kijkt.

**Comment by Valo13** [comment]
That is because the syntax highlighting colours are set manually with a white background in mind. After a bit of investigation it seems to be possible in Qt to detect whether the colour palette has changed; this could be used to trigger a change in the highlighting colour. I'll add it to the mcrl2ide todolist (issue #1484).
Would you also prefer to see the icons changed in dark mode or are they visible enough?

**Comment by jkeiren** [comment]
As far as I am concerned, the icons are acceptable in dark mode, and in particular the text needs improvement. However, if it is not too much work, you may consider having alternative icons for dark mode as well.

**Comment by jgroote** [comment]
It appears that Qt already detects for "normal text" that there is a switch from dark to light mode. 
Would it be possible to set the colors used in these tools to colors derived from the window system,
such that they change automatically without having to do much work yourself. 

Regarding icons, I am very much in favour of doing the minimal work necessary. Therefore, I would 
suggest not to adapt the icons, or change them such they are readable in light and dark mode without
adapting them dynamically. Every extra line of code will bite back eventually.

**Comment by Valo13** [comment]
I have just committed a change to mcrl2ide that might solve this issue. When the background of the text editor is/becomes a darker colour, the syntax highlighting should be different (what was black should be white and all else should be somewhat lighter).
However, as I do not own a mac, I cannot test it. Could someone with a mac test this by doing the following:
 - open mcrl2ide in light mode
 - open mcrl2ide in dark mode
 - change between light and dark mode while mcrl2ide is open
and then report on observations here?

**Comment by Valo13** [comment]
I have been able to test the above commits on Maurice's machine and to me it seems that syntax highlighting in dark mode in mcrl2ide looks fine now. Can you confirm that @jkeiren?

**Comment by jkeiren** [comment]
The issue is now indeed resolved in mcr2ide.

However, the issue persists in mcrl2xi.

**Comment by jgroote** [comment]
@Valo13 I would appreciate it if you can also rectify this in mcrl2xi. Most likely that works in exactly the same way.

**Comment by jkeiren** [comment]
I also checked the other GUI tools, and the following issues still pop up here:

**mCRL2-gui**
In mCRL2-gui in dark mode on macOS, the logging tab and the console are hard to read due to black text on a dark background. See the following screenshot:

![Screenshot 2019-08-14 at 09 45 38](https://user-images.githubusercontent.com/2182862/63003385-4c7b1b00-be78-11e9-8c12-3a7b0b193852.png)

**LTSgraph**
In LTSgraph, when enabling mCRL2 output from the View menu, the additional output is hard to read. See the following screenshot:

![Screenshot 2019-08-14 at 09 51 26](https://user-images.githubusercontent.com/2182862/63003738-25711900-be79-11e9-9376-535699d2cab6.png)

**Comment by Valo13** [comment]
Could you test mcrl2-gui and ltsgraph again with the latest commit?

**Comment by jkeiren** [comment]
> Could you test mcrl2-gui and ltsgraph again with the latest commit?

No change here. The text in the status bar at the bottom of the window is now printed in white, however (I am not sure that was the case previously).

**Comment by Valo13** [comment]
I accidentally swapped the colours, logwidgets should have white text now in case of a black background

**Comment by Valo13** [comment]
Same for the logging in a tool instance in mcrl2-gui

**Comment by jkeiren** [comment]
mcrl2-gui and lts-graph now both work for me.

**Comment by tneele** [comment]
@Valo13 Perhaps it's an idea to introduce a utility function to reduce many duplications of the following code:
https://github.com/mCRL2org/mCRL2/blob/ce7f1b4389784a8af2b9e4a73b9f85b5c87f765d/tools/release/mcrl2-gui/toolinstance.cpp#L365-L372
You can either move this whole if-statement to this new function, or at least move the expression `m_ui.edtOutput->palette().window().color().red() > 128` there.
I suggest something like
```
void setTextColorPalette(QObject* element, QColor light, QColor dark);
```

**Comment by Valo13** [comment]
@tneele I understand and thought about this as well, however I could not find a suitable location for declaring such a function. My preference would be to put it in some mcrl2/gui/utilities file, but such a file does not exist and it does not feel right to me to create such a utilities file solely containing this function.

**Comment by tneele** [comment]
That's exactly the right place, IMO. It's not a surprise that such a file does not exist yet, since the GUI tools do not share a lot of code. Feel free to create it. It's no problem if a file is small, take a look at `mcrl2/utilities/unused.h`, for example.

**Comment by Valo13** [comment]
@jkeiren I just made a commit that should fix the syntax highlighting in mcrl2xi, could you check whether it works properly on your end?

**Comment by jkeiren** [comment]
@Valo13, your latest commit resolves the issue for me. Note that a nice side effect is that it fixes the scaling/positioning of the line numbers when zooming as well.
